"use client";

import Header from "@/components/Header";
import LandingHero from "@/components/LandingHero";
import LandingTrust from "@/components/LandingTrust";
import LandingSolution from "@/components/LandingSolution";
import LandingHowItWorks from "@/components/LandingHowItWorks";
import CategoryCarousel from "@/components/CategoryCarousel";
import Footer from "@/components/Footer";
import { Button } from "@/components/Button";
import { useRouter } from "next/navigation";

export default function AboutPage() {
    const router = useRouter();

    return (
        <div className="flex flex-col min-h-screen bg-background text-foreground">
            <Header />

            <main className="flex flex-col">
                {/* 1. HERO - Hook */}
                <LandingHero onStartDemo={() => router.push("/")} />

                {/* 2. PAIN POINTS / TRUST */}
                <LandingTrust />

                {/* 3. SOLUTION - The Guide */}
                <LandingSolution />

                {/* 4. HOW IT WORKS - The Plan */}
                <LandingHowItWorks />

                {/* 5. CONTENT PREVIEW */}
                <section id="vibe-check" className="py-24 bg-secondary/5">
                    <div className="container-minimal px-4 text-center mb-12">
                        <span className="text-xs font-bold uppercase tracking-widest text-primary mb-2 block animate-pulse">
                            ▼ Live Examples
                        </span>
                        <h2 className="text-3xl md:text-5xl font-black tracking-tight mb-4">
                            Explore the Library
                        </h2>
                        <p className="text-xl text-muted-foreground text-balance max-w-2xl mx-auto">
                            Real scenarios generated by high-functioning professionals. Click to analyze the subtext.
                        </p>
                    </div>
                    <div className="container-minimal px-4">
                        <CategoryCarousel variant="minimal" disableLinks={true} />
                    </div>
                </section>
                
                {/* EXTRA CTA BUTTON */}
                <div className="flex justify-center pb-20 -mt-10 bg-secondary/5">
                    <Button 
                        onClick={() => router.push("/")}
                        className="h-auto rounded-full px-10 py-4 text-lg font-bold bg-primary text-primary-foreground hover:bg-primary/90 hover:scale-[1.02] active:scale-[0.98] transition-all shadow-xl"
                    >
                        Try it Now (Free)
                    </Button>
                </div>

                <Footer />
            </main>
        </div>
    );
}
